---
exclude: |
            (?x)^(
                shared/helm/charts/.*
            )$
repos:
  # Common linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      #- id: no-commit-to-branch
      - id: check-executables-have-shebangs

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key

  # Terraform linting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--lockfile=false
          - --hook-config=--show-diff-on-failure
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: tflint
      - id: terraform-validate
      - id: terraform-fmt
      - id: shellcheck
  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
    - id: yamllint
      files: \.(yaml|yml)$
      types: [file, yaml]
  # Ansible linting
  # - repo: https://github.com/ansible/ansible-lint
  #   rev: v5.4.0
  #   hooks:
  #   - id: ansible-lint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: remove-tabs
      - id: forbid-tabs
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
  -   repo: https://github.com/hhatto/autopep8
      rev: v2.1.0
      hooks:
        -   id: autopep8
  # -   repo: https://github.com/PyCQA/flake8
  #     rev: 7.0.0
  #     hooks:
  #       - id: flake8
  #         exclude: setup.py
  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: v1.9.0
  #     hooks:
  #     - id: mypy
  #       additional_dependencies: [types-all]
  #       exclude: ^testing/resources/
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.2  # Use the sha / tag you want to point at
    hooks:
      - id: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn",
            "--fail-on=I",
            --errors-only,
            --disable=C,R
          ]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
  # - repo: https://github.com/psf/black
  #   rev: 21.7b0
  #   hooks:
  #   - id: black
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
