---
version: '3'
services:
  syslog-connect-1:
    hostname: syslog-connect-1
    container_name: syslog-connect-1
    image: lucatronlk/kafka-connect-base:latest
    ports:
      - "8083:8083"
      - "5454:5454"
    env_file:
      - ./config/base.yml
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: "syslog-connect-1"
      CONNECT_LISTENERS: "http://syslog-connect-1:8083"
      CONNECT_GROUP_ID: "syslog-connect-1"
    command:
      - /etc/confluent/docker/run

  syslog-connect-2:
    hostname: syslog-connect-2
    container_name: syslog-connect-2
    image: lucatronlk/kafka-connect-base:latest
    ports:
      - "8084:8083"
      - "5455:5454"
    env_file:
      - ./config/base.yml
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: "syslog-connect-2"
      CONNECT_LISTENERS: "http://syslog-connect-2:8084"
      CONNECT_GROUP_ID: "syslog-connect-2"
    command:
        - /etc/confluent/docker/run

  syslog-connect-3:
    hostname: syslog-connect-3
    container_name: syslog-connect-3
    image: lucatronlk/kafka-connect-base:latest
    ports:
      - "8085:8083"
      - "5456:5454"
    env_file:
      - ./config/base.yml
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: "syslog-connect-3"
      CONNECT_LISTENERS: "http://syslog-connect-3:8085"
      CONNECT_GROUP_ID: "syslog-connect-3"
    command:
      - /etc/confluent/docker/run

  # syslog-producer:
  #   image: confluentinc/cp-kafka:7.5.3
  #   container_name: syslog-producer
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: ""
  #   command: bash -c "echo 'This is a syslog message' | kafka-console-producer --broker-list kafka-connect-1:9092,kafka-connect-2:9092 --topic syslog"
